language: rust
sudo: false
rust:
  - stable
env: 
  - TARGET=i686-unknown-linux-gnu
  - PKG_CONFIG_ALLOW_CROSS=1
matrix:
  fast_finish: true
before_script:
  - cd rust && cargo build --traget i686-unknown-linux-gnu
script: 
  - cd .. && cmake . && make -j4
