language: rust
sudo: true
rust:
  - stable
env: 
  - TARGET=i686-unknown-linux-gnu
  - PKG_CONFIG_ALLOW_CROSS=1
os:
  - linux
matrix:
  fast_finish: true
addons:
  apt:
    packages:
    - libssl-dev
install:
  - rustup target add i686-unknown-linux-gnu
before_script:
  - cd rust && cargo build --target i686-unknown-linux-gnu
script: 
  - cd .. && cmake . && make -j4
