language: rust
rust:
  - stable
matrix:
  - os: linux
    rust: stable
    env: 
      - TARGET=i686-unknown-linux-gnu
      - PKG_CONFIG_ALLOW_CROSS=1 
  fast_finish: true
script: 
  - cmake . && make -j4