language: rust
sudo: false
rust:
  - stable
env: 
  - TARGET=i686-unknown-linux-gnu
  - PKG_CONFIG_ALLOW_CROSS=1
os:
  - linux
  - osx
matrix:
  fast_finish: true
before_script:
  - rustup target add i686-unknown-linux-gnu
  - cd rust && cargo build --target i686-unknown-linux-gnu
script: 
  - cd .. && cmake . && make -j4
