language: rust
sudo: true
rust:
  - stable
env: 
  - TARGET=i686-unknown-linux-gnu
  - PKG_CONFIG_ALLOW_CROSS=1
os:
  - linux
  - osx
matrix:
  fast_finish: true
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libssl-dev
install:
  - sudo apt-get install libssl-dev
  - rustup target add i686-unknown-linux-gnu
before_script:
  - cd rust && cargo build --target i686-unknown-linux-gnu
script: 
  - cd .. && cmake . && make -j4
