[package]
name = "grip-rust"
version = "0.1.0"
authors = ["alik"]

[lib]
crate-type = ["staticlib"]

[profile.release]
lto = true

[dependencies]
bytes = "0.4.11"
crossbeam-channel = "0.3.2"
hyper-tls = "0.3.1"
futures = "0.1.25"
hyper = "0.12.16"
derive_more = "0.13.0"
libc = "0.2.43"
tokio = "0.1.11"
derive_builder = "0.7.0"
